import CoreGraphics
import CoreText
import SwiftUI
#if canImport(UIKit)
import UIKit
public typealias YallaNativeFont = UIFont
#elseif canImport(AppKit)
import AppKit
public typealias YallaNativeFont = NSFont
#endif
import YallaResourcesIOS

// Generated by yalla-design. Do not edit manually.

public struct YallaTextStyle: Sendable {
    public let fontResourceName: String
    public let size: CGFloat
    public let lineHeight: CGFloat

    public init(fontResourceName: String, size: CGFloat, lineHeight: CGFloat) {
        self.fontResourceName = fontResourceName
        self.size = size
        self.lineHeight = lineHeight
    }

    public var nativeFont: YallaNativeFont {
        if let url = YallaResourcesIOS.fontURL(fontResourceName),
           let provider = CGDataProvider(url: url as CFURL),
           let cgFont = CGFont(provider) {
            let ctFont = CTFontCreateWithGraphicsFont(cgFont, size, nil, nil)
            let descriptor = CTFontCopyFontDescriptor(ctFont)
            #if canImport(UIKit)
            return UIFont(descriptor: descriptor as UIFontDescriptor, size: size)
            #elseif canImport(AppKit)
            return NSFont(descriptor: descriptor as NSFontDescriptor, size: size) ?? NSFont.systemFont(ofSize: size)
            #endif
        }
        #if canImport(UIKit)
        return UIFont.systemFont(ofSize: size)
        #elseif canImport(AppKit)
        return NSFont.systemFont(ofSize: size)
        #endif
    }

    #if canImport(UIKit)
    public var uiFont: UIFont { nativeFont }
    #elseif canImport(AppKit)
    public var nsFont: NSFont { nativeFont }
    #endif

    public var swiftUIFont: Font {
        Font.custom(fontResourceName, size: size)
    }
}

public enum YallaFonts {
    public enum Title {
        public static let xLarge = YallaTextStyle(fontResourceName: "sfpro_bold", size: 30, lineHeight: 30)
        public static let large = YallaTextStyle(fontResourceName: "sfpro_bold", size: 22, lineHeight: 22)
        public static let base = YallaTextStyle(fontResourceName: "sfpro_bold", size: 20, lineHeight: 20)
    }

    public enum Body {
        public static let caption = YallaTextStyle(fontResourceName: "sfpro_medium", size: 13, lineHeight: 15.6)

        public enum Large {
            public static let regular = YallaTextStyle(fontResourceName: "sfpro_normal", size: 18, lineHeight: 21.6)
            public static let medium = YallaTextStyle(fontResourceName: "sfpro_medium", size: 18, lineHeight: 21.6)
            public static let bold = YallaTextStyle(fontResourceName: "sfpro_bold", size: 18, lineHeight: 21.6)
        }
        public enum Base {
            public static let regular = YallaTextStyle(fontResourceName: "sfpro_normal", size: 16, lineHeight: 20.8)
            public static let medium = YallaTextStyle(fontResourceName: "sfpro_medium", size: 16, lineHeight: 20.8)
            public static let bold = YallaTextStyle(fontResourceName: "sfpro_bold", size: 16, lineHeight: 20.8)
        }
        public enum Small {
            public static let regular = YallaTextStyle(fontResourceName: "sfpro_normal", size: 14, lineHeight: 15.4)
            public static let medium = YallaTextStyle(fontResourceName: "sfpro_medium", size: 14, lineHeight: 15.4)
            public static let bold = YallaTextStyle(fontResourceName: "sfpro_bold", size: 14, lineHeight: 15.4)
        }
    }

    public enum Custom {
        public static let carNumber = YallaTextStyle(fontResourceName: "nummernschild", size: 12, lineHeight: 16)
    }
}
