import SwiftUI
#if canImport(UIKit)
import UIKit
public typealias YallaNativeColor = UIColor
#elseif canImport(AppKit)
import AppKit
public typealias YallaNativeColor = NSColor
#endif

// Generated by yalla-design. Do not edit manually.

public enum YallaUIColor {
    public static let textBase: YallaNativeColor = dynamic(light: 0xFF101828, dark: 0xFFFFFFFF)
    public static let textSubtle: YallaNativeColor = dynamic(light: 0xFF98A2B3, dark: 0xFF747C8B)
    public static let textLink: YallaNativeColor = dynamic(light: 0xFF562DF8, dark: 0xFF562DF8)
    public static let textRed: YallaNativeColor = dynamic(light: 0xFFF42500, dark: 0xFFF42500)
    public static let textWhite: YallaNativeColor = dynamic(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
    public static let backgroundBase: YallaNativeColor = dynamic(light: 0xFFFFFFFF, dark: 0xFF1A1A20)
    public static let backgroundBrand: YallaNativeColor = dynamic(light: 0xFF562DF8, dark: 0xFF562DF8)
    public static let backgroundSecondary: YallaNativeColor = dynamic(light: 0xFFF7F7F7, dark: 0xFF21222B)
    public static let backgroundTertiary: YallaNativeColor = dynamic(light: 0xFFE9EAEA, dark: 0xFF1D1D26)
    public static let borderDisabled: YallaNativeColor = dynamic(light: 0xFFE4E7EC, dark: 0xFF383843)
    public static let borderFilled: YallaNativeColor = dynamic(light: 0xFF101828, dark: 0xFFFFFFFF)
    public static let borderWhite: YallaNativeColor = dynamic(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
    public static let borderError: YallaNativeColor = dynamic(light: 0xFFF42500, dark: 0xFFF42500)
    public static let buttonActive: YallaNativeColor = dynamic(light: 0xFF562DF8, dark: 0xFF562DF8)
    public static let buttonDisabled: YallaNativeColor = dynamic(light: 0xFFC8CBFA, dark: 0xFF2C2D34)
    public static let buttonSecondary: YallaNativeColor = dynamic(light: 0xFFF7F7F7, dark: 0xFFF7F7F7)
    public static let buttonTertiary: YallaNativeColor = dynamic(light: 0xFF101828, dark: 0xFFFFFFFF)
    public static let buttonDisabledTertiary: YallaNativeColor = dynamic(light: 0xFFCBD2E1, dark: 0xFFCBD2E1)
    public static let iconWhite: YallaNativeColor = dynamic(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
    public static let iconBase: YallaNativeColor = dynamic(light: 0xFF101828, dark: 0xFFFFFFFF)
    public static let iconSecondary: YallaNativeColor = dynamic(light: 0xFF562DF8, dark: 0xFF562DF8)
    public static let iconDisabled: YallaNativeColor = dynamic(light: 0xFFC8CBFA, dark: 0xFF2C2D34)
    public static let iconRed: YallaNativeColor = dynamic(light: 0xFFF42500, dark: 0xFFF42500)
    public static let iconSubtle: YallaNativeColor = dynamic(light: 0xFF98A2B3, dark: 0xFF98A2B3)
    public static let accentPinkSun: YallaNativeColor = fixed(0xFFFF234B)
    public static let accentColor1: YallaNativeColor = fixed(0xFFFFD1D2)
    public static let accentColor2: YallaNativeColor = fixed(0xFFCADDFF)
    public static let accentColor3: YallaNativeColor = fixed(0xFFFFDFAB)
    public static let accentColor4: YallaNativeColor = fixed(0xFFA7FFF9)
    public static let accentColor5: YallaNativeColor = fixed(0xFFD6C8FF)
    public static let gradientSplash: [YallaNativeColor] = [fixed(0xFF7957FF), fixed(0xFF562DF8), fixed(0xFF3812CE)]
    public static let gradientSunsetNight: [YallaNativeColor] = [fixed(0xFFFF234B), fixed(0xFF2F00EC)]

    private static func dynamic(light: UInt32, dark: UInt32) -> YallaNativeColor {
        #if canImport(UIKit)
        return UIColor { traitCollection in
            return traitCollection.userInterfaceStyle == .dark ? color(dark) : color(light)
        }
        #elseif canImport(AppKit)
        return NSColor(name: nil) { appearance in
            let bestMatch = appearance.bestMatch(from: [.aqua, .darkAqua])
            return bestMatch == .darkAqua ? color(dark) : color(light)
        }
        #endif
    }

    private static func fixed(_ argb: UInt32) -> YallaNativeColor {
        return color(argb)
    }

    private static func color(_ argb: UInt32) -> YallaNativeColor {
        #if canImport(UIKit)
        return UIColor(
            red: CGFloat((argb >> 16) & 0xFF) / 255.0,
            green: CGFloat((argb >> 8) & 0xFF) / 255.0,
            blue: CGFloat(argb & 0xFF) / 255.0,
            alpha: CGFloat((argb >> 24) & 0xFF) / 255.0
        )
        #elseif canImport(AppKit)
        return NSColor(
            red: CGFloat((argb >> 16) & 0xFF) / 255.0,
            green: CGFloat((argb >> 8) & 0xFF) / 255.0,
            blue: CGFloat(argb & 0xFF) / 255.0,
            alpha: CGFloat((argb >> 24) & 0xFF) / 255.0
        )
        #endif
    }
}

public enum YallaColor {
    public static let textBase: Color = platformColor(YallaUIColor.textBase)
    public static let textSubtle: Color = platformColor(YallaUIColor.textSubtle)
    public static let textLink: Color = platformColor(YallaUIColor.textLink)
    public static let textRed: Color = platformColor(YallaUIColor.textRed)
    public static let textWhite: Color = platformColor(YallaUIColor.textWhite)
    public static let backgroundBase: Color = platformColor(YallaUIColor.backgroundBase)
    public static let backgroundBrand: Color = platformColor(YallaUIColor.backgroundBrand)
    public static let backgroundSecondary: Color = platformColor(YallaUIColor.backgroundSecondary)
    public static let backgroundTertiary: Color = platformColor(YallaUIColor.backgroundTertiary)
    public static let borderDisabled: Color = platformColor(YallaUIColor.borderDisabled)
    public static let borderFilled: Color = platformColor(YallaUIColor.borderFilled)
    public static let borderWhite: Color = platformColor(YallaUIColor.borderWhite)
    public static let borderError: Color = platformColor(YallaUIColor.borderError)
    public static let buttonActive: Color = platformColor(YallaUIColor.buttonActive)
    public static let buttonDisabled: Color = platformColor(YallaUIColor.buttonDisabled)
    public static let buttonSecondary: Color = platformColor(YallaUIColor.buttonSecondary)
    public static let buttonTertiary: Color = platformColor(YallaUIColor.buttonTertiary)
    public static let buttonDisabledTertiary: Color = platformColor(YallaUIColor.buttonDisabledTertiary)
    public static let iconWhite: Color = platformColor(YallaUIColor.iconWhite)
    public static let iconBase: Color = platformColor(YallaUIColor.iconBase)
    public static let iconSecondary: Color = platformColor(YallaUIColor.iconSecondary)
    public static let iconDisabled: Color = platformColor(YallaUIColor.iconDisabled)
    public static let iconRed: Color = platformColor(YallaUIColor.iconRed)
    public static let iconSubtle: Color = platformColor(YallaUIColor.iconSubtle)
    public static let accentPinkSun: Color = platformColor(YallaUIColor.accentPinkSun)
    public static let accentColor1: Color = platformColor(YallaUIColor.accentColor1)
    public static let accentColor2: Color = platformColor(YallaUIColor.accentColor2)
    public static let accentColor3: Color = platformColor(YallaUIColor.accentColor3)
    public static let accentColor4: Color = platformColor(YallaUIColor.accentColor4)
    public static let accentColor5: Color = platformColor(YallaUIColor.accentColor5)

    private static func platformColor(_ color: YallaNativeColor) -> Color {
        #if canImport(UIKit)
        return Color(uiColor: color)
        #elseif canImport(AppKit)
        return Color(nsColor: color)
        #endif
    }
}
