import SwiftUI
#if canImport(UIKit)
import UIKit
#elseif canImport(AppKit)
import AppKit
#endif
import YallaResourcesIOS

// Generated by yalla-design. Do not edit manually.

public enum YallaThemedImage: String, CaseIterable, Sendable {
    case blurryLogo = "BlurryLogo"
    case closeCircle = "CloseCircle"
    case login = "Login"
    case logout = "Logout"
    case mapPin = "MapPin"
    case notificationMute = "NotificationMute"
    case orderHistory = "OrderHistory"
    case orderSearch = "OrderSearch"
    case safety = "Safety"
    case shieldCheck = "ShieldCheck"
    case tariffCard = "TariffCard"
    case trashCan = "TrashCan"

    public var assetName: String {
        switch self {
        case .blurryLogo: return "img_blurry_logo"
        case .closeCircle: return "img_close_circle"
        case .login: return "img_login"
        case .logout: return "img_logout"
        case .mapPin: return "img_map_pin"
        case .notificationMute: return "img_notification_mute"
        case .orderHistory: return "img_order_history"
        case .orderSearch: return "img_order_search"
        case .safety: return "img_safety"
        case .shieldCheck: return "img_shield_check"
        case .tariffCard: return "img_tariff_card"
        case .trashCan: return "img_trash_can"
        }
    }

    #if canImport(UIKit)
    public func uiImage(compatibleWith traitCollection: UITraitCollection? = nil) -> UIImage? {
        return YallaResourcesIOS.platformImage(assetName, compatibleWith: traitCollection)
    }
    #elseif canImport(AppKit)
    public func nsImage() -> NSImage? {
        return YallaResourcesIOS.platformImage(assetName)
    }
    #endif

    @available(iOS 13.0, macOS 10.15, *)
    public var image: Image {
        YallaResourcesIOS.swiftUIImage(assetName)
    }
}
