import SwiftUI
#if canImport(UIKit)
import UIKit
#elseif canImport(AppKit)
import AppKit
#endif
import YallaResourcesIOS

// Generated by yalla-design. Do not edit manually.

public enum YallaThemedImage: String, CaseIterable, Sendable {
    case blurryLogo = "BlurryLogo"
    case closeCircle = "CloseCircle"
    case login = "Login"
    case logout = "Logout"
    case mapPin = "MapPin"
    case notificationMute = "NotificationMute"
    case orderHistory = "OrderHistory"
    case orderSearch = "OrderSearch"
    case safety = "Safety"
    case shieldCheck = "ShieldCheck"
    case tariffCard = "TariffCard"
    case trashCan = "TrashCan"

    public var assetName: String {
        switch self {
        case .blurryLogo:
            return "yalla_img_blurry_logo"
        case .closeCircle:
            return "yalla_img_close_circle"
        case .login:
            return "yalla_img_login"
        case .logout:
            return "yalla_img_logout"
        case .mapPin:
            return "yalla_img_map_pin"
        case .notificationMute:
            return "yalla_img_notification_mute"
        case .orderHistory:
            return "yalla_img_order_history"
        case .orderSearch:
            return "yalla_img_order_search"
        case .safety:
            return "yalla_img_safety"
        case .shieldCheck:
            return "yalla_img_shield_check"
        case .tariffCard:
            return "yalla_img_tariff_card"
        case .trashCan:
            return "yalla_img_trash_can"
        }
    }

    #if canImport(UIKit)
    public func uiImage(compatibleWith traitCollection: UITraitCollection? = nil) -> UIImage? {
        return YallaResourcesIOS.platformImage(assetName, compatibleWith: traitCollection)
    }
    #elseif canImport(AppKit)
    public func nsImage() -> NSImage? {
        return YallaResourcesIOS.platformImage(assetName)
    }
    #endif

    @available(iOS 13.0, macOS 10.15, *)
    public var image: Image {
        YallaResourcesIOS.swiftUIImage(assetName)
    }
}
